# Example HPA with Auto-Discovery Annotations
# 
# Smart Autoscaler will automatically discover and manage HPAs
# that have the annotation: smart-autoscaler.io/enabled: "true"
#
# Supported annotations:
#   smart-autoscaler.io/enabled: "true"          # Required - enables auto-discovery
#   smart-autoscaler.io/priority: "high"         # Optional - priority level (critical, high, medium, low, best_effort)
#   smart-autoscaler.io/startup-filter: "2"      # Optional - startup filter in minutes (default: 2)

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-server-hpa
  namespace: production
  annotations:
    # Enable auto-discovery by Smart Autoscaler
    smart-autoscaler.io/enabled: "true"
    # Set priority to high (faster scaling, more headroom)
    smart-autoscaler.io/priority: "high"
    # Ignore scaling events in first 3 minutes after pod start
    smart-autoscaler.io/startup-filter: "3"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-server
  minReplicas: 2
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: worker-hpa
  namespace: production
  annotations:
    smart-autoscaler.io/enabled: "true"
    smart-autoscaler.io/priority: "medium"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: worker
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: payment-hpa
  namespace: production
  annotations:
    smart-autoscaler.io/enabled: "true"
    # Critical priority for payment processing
    smart-autoscaler.io/priority: "critical"
    # Longer startup filter for payment service
    smart-autoscaler.io/startup-filter: "5"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: payment-service
  minReplicas: 3
  maxReplicas: 15
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60

---
# Example HPA WITHOUT auto-discovery (will be ignored by Smart Autoscaler)
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: internal-tool-hpa
  namespace: tools
  # No smart-autoscaler.io/enabled annotation = not managed
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: internal-tool
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
